# 准备

## 区别实例对象与函数对象

实例对象：new 构造函数产生的对象称为实例对象，简称为对象。

函数对象：将函数作为对象使用时，简称为函数对象

```js
function Fn(){
  // 我是函数
}
Fn.bind({}); // Fn是函数对象
const fn = new Fn(); // Fn是构造函数 fn是实例对象
```

> 速记：括号左边是函数，点的左边是对象。



## 两种类型的回调函数

### 什么是回调函数？

**回调函数是你写一个函数，让预先写好的系统来调用。你调用系统的函数，是直调。让系统调用你的函数，就是回调。**

回调函数满足的三个条件：

- 你定义的
- 你没有调用
- 但它自己执行了



### 同步回调

理解：立即执行，完全执行完了才结束，不会放入回调队列中

例子：数组遍历相关的回调、Promise的excutor函数

```js
const arr = [1, 3, 5, 7, 9];
// 遍历回调 => 同步回调函数
arr.forEach(item => {
  console.log(item);
})
console.log('forEach()之后');
```



### 异步回调

理解：不会立即执行，会放入回调队列中将来执行。

例子：定时器回调、ajax回调、Promise的成功失败回调

```js
setTimeout(() => {
  console.log("timeout callback");
}, 0);
console.log("setTimeout()之后");
```



## js的error处理

### 错误类型

| 错误类型       | 解释                       | message                                                      |
| -------------- | -------------------------- | ------------------------------------------------------------ |
| Error          | 所有错误的父类型           |                                                              |
| ReferenceError | 引用的变量不存在           | Uncaught ReferenceError：xxx is not defined<br/>（未捕获的引用错误：xxx 是未被定义的） |
| TypeError      | 数据类型不正确的错误       | Uncaught TypeError：Cannot read property 'xxx' of undefined<br>（未捕获的类型错误：你不能在undefined上去读取xxx属性） |
| RangeError     | 数据值不在其所允许的范围内 | Uncaught RangeError：Maximum call stack size exceeded<br>（未捕获的范围错误：超过最大调用堆栈大小） |
| SyntaxError    | 语法错误                   | Uncaught SyntaxError：Unexpected string<br>（未捕获的语法错误：意想不到的字符串） |

### 错误处理

捕获错误 `try...catch`

```js
try {
  	let a;
    console.log(a.xxx);
} catch (error) {
    console.dir(error);
}
console.log('出错之后');
```

抛出错误 `throw error`

```js
// 抛出错误
function something() {
  if (Date.now() % 2 === 1) {
    console.log("当前时间为奇数");
  } else {
    throw new Error("当前时间为偶数");
  }
}

// 捕获错误
try {
  something();
} catch (error) {
  alert(error.message);
}
```



### 错误对象

```js
try {
    console.log(a);
} catch (error) {
  	// message属性：错误相关信息
    console.log(error.message);
  	// stack属性：函数调用栈记录信息
  	console.log(error.stack);
}
```

